# Generated by Django 3.1.6 on 2021-02-26 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.FloatField()),
                ('neg', models.FloatField()),
                ('neu', models.FloatField()),
                ('comp', models.FloatField()),
                ('brand', models.CharField(max_length=40)),
                ('day', models.DateField()),
                ('ticker', models.CharField(max_length=40)),
                ('closeprice', models.FloatField()),
                ('SMA5', models.FloatField()),
                ('EMA', models.FloatField()),
                ('fut1', models.FloatField()),
                ('fut2', models.FloatField()),
                ('fut3', models.FloatField()),
                ('fut4', models.FloatField()),
                ('fut5', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_sentiment', models.FloatField()),
                ('p_5day', models.FloatField()),
                ('p_5dayEMA', models.FloatField()),
                ('p_EMA', models.FloatField()),
                ('p_sentimentEMA', models.FloatField()),
                ('p_realprice', models.FloatField()),
                ('brand', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='TestQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.question')),
            ],
        ),
    ]
